/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChessbordGo: typeof import('./src/components/ChessboardGo/ChessbordGo.vue')['default']
    ChessbordGomoku: typeof import('./src/components/ChessboardGomoku/ChessbordGomoku.vue')['default']
    Empty: typeof import('./src/components/empty.vue/empty.vue')['default']
    MaslowGochessboard: typeof import('./src/components/maslow-gochessboard/maslow-gochessboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButotn: typeof import('vant/es')['Butotn']
    VanButton: typeof import('vant/es')['Button']
    VanSlider: typeof import('vant/es')['Slider']
    VipLabel: typeof import('./src/components/VipLabel/VipLabel.vue')['default']
  }
}
